# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  node: "20.10.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-xml
      - id: check-json
        files: '\.json$'
        exclude: 'frontend|tsconfig.json'
      - id: check-shebang-scripts-are-executable
        exclude: '\.inc$'
      - id: trailing-whitespace
        exclude: '.*/schema/docs/.*|.*/afg_platform/v.*/generated/.*|.*/__snapshots__/.*|.*/fixtures/csv_data/.*$'
      - id: end-of-file-fixer
        files: '\.py$'
      - id: check-added-large-files
        exclude: '\.xsd$|.*/schema/docs/.*$|.*/schema/generated/.*$'

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf
        exclude: '.*/fixtures/csv_data/.*$'
      - id: forbid-tabs
        files: '\.py$|\.js$|\.less$|\.html$'
        exclude: '.*/schema/docs/.*$'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
        types_or: [ python, pyi ]
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format
        types: [file, python]
