# render.yaml
services:
  - type: web
    name: eventsky
    env: python
    region: singapore
    plan: starter
    autoDeploy: true
    healthCheckPath: /healthz

    envVars:
      - key: ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: PYTHONPATH
        value: ./src          # so "eventcloud.app" is importable
      - key: WEB_CONCURRENCY
        value: "4"            # tweak per load
      - key: POETRY_VERSION
        value: "2.0.1"

    buildCommand: |
      pip install --upgrade pip
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --only main --no-interaction --no-ansi

    preDeployCommand: alembic upgrade head

    # Gunicorn + Uvicorn workers (prod-ready)
    startCommand: >
      gunicorn -k uvicorn.workers.UvicornWorker
      -w ${WEB_CONCURRENCY:-4}
      -b 0.0.0.0:${PORT}
      eventcloud.app:app

