# render.yaml
services:
  - type: web
    name: eventsky
    env: python
    region: singapore
    plan: starter
    autoDeploy: true
    healthCheckPath: /healthz

    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: PYTHONPATH
        value: ./src          # so "eventcloud.app" is importable
      - key: WEB_CONCURRENCY
        value: "1"            # tweak per load
      - key: POETRY_VERSION
        value: "2.0.1"
      - key: HOST
        value: "https://eventsky.onrender.com"

    buildCommand: |
      pip install --upgrade pip
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --no-interaction --no-ansi


    preDeployCommand: alembic -c src/eventcloud/alembic.ini upgrade head


    startCommand: >
      uvicorn eventcloud.app:app
      --host 0.0.0.0 --port ${PORT}
      --workers ${WEB_CONCURRENCY:-4}

