"""Initial schema

Revision ID: 053f5f1ba08a
Revises:
Create Date: 2025-08-14 22:40:13.873578

"""

from typing import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "053f5f1ba08a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_code"), ["code"], unique=False)

    op.create_table(
        "eventmessages",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("sender_name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["events.code"], name="fk_eventmessages_event"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("eventmessages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_eventmessages_uuid"), ["uuid"], unique=False)

    op.create_table(
        "eventmessageimages",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("event_message_id", sa.String(), nullable=False),
        sa.Column("image_key", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_message_id"],
            ["eventmessages.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("eventmessageimages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_eventmessageimages_uuid"), ["uuid"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("eventmessageimages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eventmessageimages_uuid"))

    op.drop_table("eventmessageimages")
    with op.batch_alter_table("eventmessages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eventmessages_uuid"))

    op.drop_table("eventmessages")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_code"))

    op.drop_table("events")
    # ### end Alembic commands ###
