"""Add EventMessages

Revision ID: 0d5435ae19a9
Revises: 60a2b2208105
Create Date: 2025-08-03 17:21:41.559388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5435ae19a9'
down_revision: Union[str, Sequence[str], None] = '60a2b2208105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventmessages',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_eventmessages_uuid'), 'eventmessages', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventmessages_uuid'), table_name='eventmessages')
    op.drop_table('eventmessages')
    # ### end Alembic commands ###
