"""add pinned to eventmessage

Revision ID: 2414f6825fe9
Revises: 9f0f34108a06
Create Date: 2025-09-21 18:09:56.863788

"""

from typing import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2414f6825fe9"
down_revision: Union[str, Sequence[str], None] = "9f0f34108a06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("eventmessages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pinned", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("eventmessages", schema=None) as batch_op:
        batch_op.drop_column("pinned")

    # ### end Alembic commands ###
