"""switch primary key

Revision ID: 32463c73c335
Revises: 23730a5b0378
Create Date: 2025-09-20 00:05:50.364311

"""

from typing import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "32463c73c335"
down_revision: Union[str, Sequence[str], None] = "23730a5b0378"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.alter_column("code", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_index(batch_op.f("ix_events_code"))
        batch_op.create_index(batch_op.f("ix_events_code"), ["code"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_code"))
        batch_op.create_index(batch_op.f("ix_events_code"), ["code"], unique=False)
        batch_op.alter_column("code", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###
