"""Add EventMessages ForeignKey to Event

Revision ID: 5d59df81bd6c
Revises: 0d5435ae19a9
Create Date: 2025-08-03 17:54:55.592304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d59df81bd6c'
down_revision: Union[str, Sequence[str], None] = '0d5435ae19a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventmessages', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_eventmessages_event', 'events', ['event'], ['code'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventmessages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_eventmessages_event', type_='foreignkey')

    # ### end Alembic commands ###
