"""added sender_name

Revision ID: 905a2d313435
Revises: 9f94193b7822
Create Date: 2025-08-14 21:32:13.078749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905a2d313435'
down_revision: Union[str, Sequence[str], None] = '9f94193b7822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_eventmessages')
    with op.batch_alter_table('eventmessages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_name', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_eventmessages_event', 'events', ['event_id'], ['code'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventmessages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_eventmessages_event', type_='foreignkey')
        batch_op.drop_column('sender_name')

    op.create_table('_alembic_tmp_eventmessages',
    sa.Column('uuid', sa.VARCHAR(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('sender_name', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.code'], name=op.f('fk_eventmessages_event')),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###
