"""add_uuid and set nullable

Revision ID: 9f0f34108a06
Revises: b81673c37d72
Create Date: 2025-09-20 00:14:15.873754

"""

from typing import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9f0f34108a06"
down_revision: Union[str, Sequence[str], None] = "b81673c37d72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uuid", sa.String(), nullable=True))
        batch_op.create_index(batch_op.f("ix_events_uuid"), ["uuid"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_uuid"))
        batch_op.drop_column("uuid")

    # ### end Alembic commands ###
