"""event message image

Revision ID: 9f94193b7822
Revises: a1b425e78ac0
Create Date: 2025-08-06 00:02:27.628915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f94193b7822'
down_revision: Union[str, Sequence[str], None] = 'a1b425e78ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventmessageimages',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('event_message_id', sa.String(), nullable=False),
    sa.Column('image_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_message_id'], ['eventmessages.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('eventmessageimages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventmessageimages_uuid'), ['uuid'], unique=False)

    with op.batch_alter_table('eventmessages', schema=None) as batch_op:
        batch_op.alter_column('event', new_column_name='event_id')
        batch_op.drop_constraint(batch_op.f('fk_eventmessages_event'), type_='foreignkey')
        batch_op.create_foreign_key('fk_eventmessages_event', 'events', ['event_id'], ['code'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventmessages', schema=None) as batch_op:
        batch_op.alter_column('event_id', new_column_name='event')
        batch_op.create_foreign_key(batch_op.f('fk_eventmessages_event'), 'events', ['event'], ['code'])

    with op.batch_alter_table('eventmessageimages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventmessageimages_uuid'))

    op.drop_table('eventmessageimages')
    # ### end Alembic commands ###
