"""Add EventMessages ForeignKey to Event with default

Revision ID: a1b425e78ac0
Revises: 5d59df81bd6c
Create Date: 2025-08-03 18:04:20.632792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b425e78ac0'
down_revision: Union[str, Sequence[str], None] = '5d59df81bd6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
