"""added blurred_image_key

Revision ID: ee862287cf0a
Revises: 3007527cfdad
Create Date: 2025-10-28 19:31:44.296033

"""

from typing import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ee862287cf0a"
down_revision: Union[str, Sequence[str], None] = "3007527cfdad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("eventmessageimages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("blurred_image_key", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("eventmessageimages", schema=None) as batch_op:
        batch_op.drop_column("blurred_image_key")

    # ### end Alembic commands ###
